apiVersion: v1
kind: Service
metadata:
  name: tienda-db
  namespace: tienda
spec:
  selector:
    app: tienda-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
