name: Pipeline CI/CD - Innovatech EKS

on:
  push:
    branches: [ main ] # Se ejecuta automáticamente al hacer commit a main

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: devopseks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Images
      run: |
        # Frontend (Nginx + JS)
        docker build -t ${{ steps.login-ecr.outputs.registry }}/innovatech/frontend:latest ./frontend
        docker push ${{ steps.login-ecr.outputs.registry }}/innovatech/frontend:latest
        
        # Backend (Node.js API)
        docker build -t ${{ steps.login-ecr.outputs.registry }}/innovatech/backend:latest ./backend
        docker push ${{ steps.login-ecr.outputs.registry }}/innovatech/backend:latest

    - name: Connect to EKS Cluster
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/mysql-secret.yaml
        kubectl apply -f k8s/mysql-service.yaml
        kubectl apply -f k8s/mysql-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/backend-hpa.yaml
        kubectl apply -f k8s/frontend-hpa.yaml

    - name: Verify Rollout Status
      run: |
        kubectl rollout restart deployment/backend-deployment -n tienda
        kubectl rollout restart deployment/frontend-deployment -n tienda
        kubectl rollout status deployment/backend-deployment -n tienda